### ISSUE TITLE
/bin/bash: /etc/nginx/conf.d/st2.conf: Permission denied

### ISSUE THREAD

**Issue by Kishore1705** [StackStorm/stackstorm-k8s#405] opened 2024-03-06 10:35 UTC
when i'm trying to run st2web on openshift it requires root previelages in openshift which is not supported

**Comment by speaktoabu** [comment] 2024-03-08 20:55
After security context to run as nonuser, I'm facing this error in k8s environment

**Comment by cognifloyd** [comment] 2024-04-11 23:21
Duplicate of #185

**Closed by cognifloyd** 2024-04-11 23:21 UTC
